spring:
  application:
    name: apit-gateway
  cloud:
    gateway:
      routes:
        - id: prefixpath_route
          uri: http://localhost:8080
          predicates:
            - Path=/map
          filters:
            - RedirectTo=302, http://localhost:5000
        - id: test-get
          uri: lb://MAP-SERVICE
          predicates:
            - Path=/get-test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/