spring:
  application:
    name: apit-gateway
  cloud:
    gateway:
      routes:
        - id: map route
          uri: lb://CORONA-MAP
          predicates:
            - Path=/

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY:http://localhost:1111/eureka}