spring:
  application:
    name: apit-gateway
  cloud:
    gateway:
      routes:
        - id: prefixpath_route
          uri: lb://CORONA-MAP
          predicates:
            - Path=/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/