version: 2.1

orbs:
  gradle: circleci/gradle@2.1.0

executors:
  my-executor:
    docker:
      - image: 'cimg/openjdk:11'

workflows:
  checkout-build-test:
    jobs:
      - gradle/test:
          executor: my-executor
